name: capital_race
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  flame_svg: ^1.11.18
  flame_audio: ^2.11.12
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
